//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QuanLyTrungTamNgoaiNgu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANGKYLOP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DANGKYLOP()
        {
            this.DIEMDANHs = new HashSet<DIEMDANH>();
            this.PHIEUTHUs = new HashSet<PHIEUTHU>();
        }
    
        public string MaHV { get; set; }
        public string MALOP { get; set; }
        public System.DateTime NGAYDK { get; set; }
        public decimal HOCPHI { get; set; }
        public string TRANGTHAI { get; set; }
    
        public virtual HOCVIEN HOCVIEN { get; set; }
        public virtual LOPHOC LOPHOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIEMDANH> DIEMDANHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUTHU> PHIEUTHUs { get; set; }
    }
}
