//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QuanLyTrungTamNgoaiNgu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHOC
    {
        public int MALICH { get; set; }
        public string MALOP { get; set; }
        public System.DateTime NGAYHOC { get; set; }
        public string MAPHONG { get; set; }
        public string MACA { get; set; }
    
        public virtual CAHOC CAHOC { get; set; }
        public virtual LOPHOC LOPHOC { get; set; }
        public virtual PHONGHOC PHONGHOC { get; set; }
    }
}
