//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QuanLyTrungTamNgoaiNgu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUCHI
    {
        public string MAPC { get; set; }
        public System.DateTime NGAYCHI { get; set; }
        public decimal SOTIEN { get; set; }
        public string NOIDUNG { get; set; }
        public string MANV_LAP { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
