//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QuanLyTrungTamNgoaiNgu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTHU
    {
        public string MAPHIEU { get; set; }
        public string MaHV { get; set; }
        public string MALOP { get; set; }
        public System.DateTime NGAYTHU { get; set; }
        public decimal SOTIEN { get; set; }
        public string HINHTHUCTHU { get; set; }
        public string GHICHU { get; set; }
    
        public virtual DANGKYLOP DANGKYLOP { get; set; }
    }
}
