//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QuanLyTrungTamNgoaiNgu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QL_TRUNGTAM_TIENGANH : DbContext
    {
        public QL_TRUNGTAM_TIENGANH()
            : base("name=QL_TRUNGTAM_TIENGANH")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAHOC> CAHOCs { get; set; }
        public virtual DbSet<DANGKYLOP> DANGKYLOPs { get; set; }
        public virtual DbSet<DIEMDANH> DIEMDANHs { get; set; }
        public virtual DbSet<GIAOVIEN> GIAOVIENs { get; set; }
        public virtual DbSet<HOCVIEN> HOCVIENs { get; set; }
        public virtual DbSet<KHOA_HOC> KHOA_HOC { get; set; }
        public virtual DbSet<LICHOC> LICHOCs { get; set; }
        public virtual DbSet<LOAI_KHOAHOC> LOAI_KHOAHOC { get; set; }
        public virtual DbSet<LOPHOC> LOPHOCs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHIEUTHU> PHIEUTHUs { get; set; }
        public virtual DbSet<PHONGHOC> PHONGHOCs { get; set; }
        public virtual DbSet<QUYEN> QUYENs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual DbSet<VW_GiaoVien_SoLop> VW_GiaoVien_SoLop { get; set; }
        public virtual DbSet<VW_KhoaHoc_ThongKe> VW_KhoaHoc_ThongKe { get; set; }
        public virtual DbSet<VW_TaiKhoan_Quyen> VW_TaiKhoan_Quyen { get; set; }
        public virtual DbSet<VW_DanhSachDiemDanh> VW_DanhSachDiemDanh { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual ObjectResult<SP_CanhBaoVangNhieu_Result> SP_CanhBaoVangNhieu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CanhBaoVangNhieu_Result>("SP_CanhBaoVangNhieu");
        }
    
        public virtual int SP_CapNhatTrangThaiHocVien(string maHV, string trangThai)
        {
            var maHVParameter = maHV != null ?
                new ObjectParameter("MaHV", maHV) :
                new ObjectParameter("MaHV", typeof(string));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CapNhatTrangThaiHocVien", maHVParameter, trangThaiParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int SP_DangKyLop(string maHV, string maLop, Nullable<System.DateTime> ngayDK, Nullable<decimal> hocPhi)
        {
            var maHVParameter = maHV != null ?
                new ObjectParameter("MaHV", maHV) :
                new ObjectParameter("MaHV", typeof(string));
    
            var maLopParameter = maLop != null ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(string));
    
            var ngayDKParameter = ngayDK.HasValue ?
                new ObjectParameter("NgayDK", ngayDK) :
                new ObjectParameter("NgayDK", typeof(System.DateTime));
    
            var hocPhiParameter = hocPhi.HasValue ?
                new ObjectParameter("HocPhi", hocPhi) :
                new ObjectParameter("HocPhi", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DangKyLop", maHVParameter, maLopParameter, ngayDKParameter, hocPhiParameter);
        }
    
        public virtual int SP_DoiMatKhau(string tENDANGNHAP, string mATKHAU_CU, string mATKHAU_MOI)
        {
            var tENDANGNHAPParameter = tENDANGNHAP != null ?
                new ObjectParameter("TENDANGNHAP", tENDANGNHAP) :
                new ObjectParameter("TENDANGNHAP", typeof(string));
    
            var mATKHAU_CUParameter = mATKHAU_CU != null ?
                new ObjectParameter("MATKHAU_CU", mATKHAU_CU) :
                new ObjectParameter("MATKHAU_CU", typeof(string));
    
            var mATKHAU_MOIParameter = mATKHAU_MOI != null ?
                new ObjectParameter("MATKHAU_MOI", mATKHAU_MOI) :
                new ObjectParameter("MATKHAU_MOI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DoiMatKhau", tENDANGNHAPParameter, mATKHAU_CUParameter, mATKHAU_MOIParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int SP_HuyLop(string maLop)
        {
            var maLopParameter = maLop != null ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HuyLop", maLopParameter);
        }
    
        public virtual int SP_KhoaMoTaiKhoan(string tENDANGNHAP, Nullable<bool> tRANGTHAI)
        {
            var tENDANGNHAPParameter = tENDANGNHAP != null ?
                new ObjectParameter("TENDANGNHAP", tENDANGNHAP) :
                new ObjectParameter("TENDANGNHAP", typeof(string));
    
            var tRANGTHAIParameter = tRANGTHAI.HasValue ?
                new ObjectParameter("TRANGTHAI", tRANGTHAI) :
                new ObjectParameter("TRANGTHAI", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_KhoaMoTaiKhoan", tENDANGNHAPParameter, tRANGTHAIParameter);
        }
    
        public virtual int SP_MoLopMoi(string maLop, string tenLop, string maKH, string maGV, Nullable<System.DateTime> ngayBatDau, string maPhong, string maCa, Nullable<bool> t2, Nullable<bool> t3, Nullable<bool> t4, Nullable<bool> t5, Nullable<bool> t6, Nullable<bool> t7, Nullable<bool> cN, Nullable<int> soBuoi)
        {
            var maLopParameter = maLop != null ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(string));
    
            var tenLopParameter = tenLop != null ?
                new ObjectParameter("TenLop", tenLop) :
                new ObjectParameter("TenLop", typeof(string));
    
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            var maGVParameter = maGV != null ?
                new ObjectParameter("MaGV", maGV) :
                new ObjectParameter("MaGV", typeof(string));
    
            var ngayBatDauParameter = ngayBatDau.HasValue ?
                new ObjectParameter("NgayBatDau", ngayBatDau) :
                new ObjectParameter("NgayBatDau", typeof(System.DateTime));
    
            var maPhongParameter = maPhong != null ?
                new ObjectParameter("MaPhong", maPhong) :
                new ObjectParameter("MaPhong", typeof(string));
    
            var maCaParameter = maCa != null ?
                new ObjectParameter("MaCa", maCa) :
                new ObjectParameter("MaCa", typeof(string));
    
            var t2Parameter = t2.HasValue ?
                new ObjectParameter("T2", t2) :
                new ObjectParameter("T2", typeof(bool));
    
            var t3Parameter = t3.HasValue ?
                new ObjectParameter("T3", t3) :
                new ObjectParameter("T3", typeof(bool));
    
            var t4Parameter = t4.HasValue ?
                new ObjectParameter("T4", t4) :
                new ObjectParameter("T4", typeof(bool));
    
            var t5Parameter = t5.HasValue ?
                new ObjectParameter("T5", t5) :
                new ObjectParameter("T5", typeof(bool));
    
            var t6Parameter = t6.HasValue ?
                new ObjectParameter("T6", t6) :
                new ObjectParameter("T6", typeof(bool));
    
            var t7Parameter = t7.HasValue ?
                new ObjectParameter("T7", t7) :
                new ObjectParameter("T7", typeof(bool));
    
            var cNParameter = cN.HasValue ?
                new ObjectParameter("CN", cN) :
                new ObjectParameter("CN", typeof(bool));
    
            var soBuoiParameter = soBuoi.HasValue ?
                new ObjectParameter("SoBuoi", soBuoi) :
                new ObjectParameter("SoBuoi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MoLopMoi", maLopParameter, tenLopParameter, maKHParameter, maGVParameter, ngayBatDauParameter, maPhongParameter, maCaParameter, t2Parameter, t3Parameter, t4Parameter, t5Parameter, t6Parameter, t7Parameter, cNParameter, soBuoiParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int SP_TaoTaiKhoan(string mATK, string tENDANGNHAP, string mATKHAU, string maNV, string maGV, string chuoiQuyen)
        {
            var mATKParameter = mATK != null ?
                new ObjectParameter("MATK", mATK) :
                new ObjectParameter("MATK", typeof(string));
    
            var tENDANGNHAPParameter = tENDANGNHAP != null ?
                new ObjectParameter("TENDANGNHAP", tENDANGNHAP) :
                new ObjectParameter("TENDANGNHAP", typeof(string));
    
            var mATKHAUParameter = mATKHAU != null ?
                new ObjectParameter("MATKHAU", mATKHAU) :
                new ObjectParameter("MATKHAU", typeof(string));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var maGVParameter = maGV != null ?
                new ObjectParameter("MaGV", maGV) :
                new ObjectParameter("MaGV", typeof(string));
    
            var chuoiQuyenParameter = chuoiQuyen != null ?
                new ObjectParameter("ChuoiQuyen", chuoiQuyen) :
                new ObjectParameter("ChuoiQuyen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TaoTaiKhoan", mATKParameter, tENDANGNHAPParameter, mATKHAUParameter, maNVParameter, maGVParameter, chuoiQuyenParameter);
        }
    
        public virtual int SP_ThemHocVien(string maHV, string hoTen, Nullable<System.DateTime> ngaySinh, string gioiTinh, string diaChi, string sDT, string email)
        {
            var maHVParameter = maHV != null ?
                new ObjectParameter("MaHV", maHV) :
                new ObjectParameter("MaHV", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ThemHocVien", maHVParameter, hoTenParameter, ngaySinhParameter, gioiTinhParameter, diaChiParameter, sDTParameter, emailParameter);
        }
    
        public virtual int SP_ThemKhoaHoc(string mAKH, string tENKH, Nullable<int> sOBUOI, Nullable<decimal> hOCPHI_GD, string mALOAI_KH)
        {
            var mAKHParameter = mAKH != null ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(string));
    
            var tENKHParameter = tENKH != null ?
                new ObjectParameter("TENKH", tENKH) :
                new ObjectParameter("TENKH", typeof(string));
    
            var sOBUOIParameter = sOBUOI.HasValue ?
                new ObjectParameter("SOBUOI", sOBUOI) :
                new ObjectParameter("SOBUOI", typeof(int));
    
            var hOCPHI_GDParameter = hOCPHI_GD.HasValue ?
                new ObjectParameter("HOCPHI_GD", hOCPHI_GD) :
                new ObjectParameter("HOCPHI_GD", typeof(decimal));
    
            var mALOAI_KHParameter = mALOAI_KH != null ?
                new ObjectParameter("MALOAI_KH", mALOAI_KH) :
                new ObjectParameter("MALOAI_KH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ThemKhoaHoc", mAKHParameter, tENKHParameter, sOBUOIParameter, hOCPHI_GDParameter, mALOAI_KHParameter);
        }
    
        public virtual ObjectResult<SP_ThongKeLopTheoKhoaHoc_Result> SP_ThongKeLopTheoKhoaHoc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ThongKeLopTheoKhoaHoc_Result>("SP_ThongKeLopTheoKhoaHoc");
        }
    
        public virtual int SP_ThuHocPhi(string maPhieu, string maHV, string maLop, Nullable<decimal> soTien, Nullable<System.DateTime> ngayThu, string hinhThuc, string ghiChu)
        {
            var maPhieuParameter = maPhieu != null ?
                new ObjectParameter("MaPhieu", maPhieu) :
                new ObjectParameter("MaPhieu", typeof(string));
    
            var maHVParameter = maHV != null ?
                new ObjectParameter("MaHV", maHV) :
                new ObjectParameter("MaHV", typeof(string));
    
            var maLopParameter = maLop != null ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(string));
    
            var soTienParameter = soTien.HasValue ?
                new ObjectParameter("SoTien", soTien) :
                new ObjectParameter("SoTien", typeof(decimal));
    
            var ngayThuParameter = ngayThu.HasValue ?
                new ObjectParameter("NgayThu", ngayThu) :
                new ObjectParameter("NgayThu", typeof(System.DateTime));
    
            var hinhThucParameter = hinhThuc != null ?
                new ObjectParameter("HinhThuc", hinhThuc) :
                new ObjectParameter("HinhThuc", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ThuHocPhi", maPhieuParameter, maHVParameter, maLopParameter, soTienParameter, ngayThuParameter, hinhThucParameter, ghiChuParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
