//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QuanLyTrungTamNgoaiNgu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_GiaoVien_SoLop
    {
        public string MaGV { get; set; }
        public string TenGV { get; set; }
        public string TrinhDo { get; set; }
        public Nullable<int> SoLopDangDay { get; set; }
    }
}
