//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QuanLyTrungTamNgoaiNgu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_KhoaHoc_ThongKe
    {
        public string MAKH { get; set; }
        public string TENKH { get; set; }
        public string TENLOAI { get; set; }
        public int SOBUOI { get; set; }
        public decimal HOCPHI_GD { get; set; }
        public Nullable<int> TongSoLop { get; set; }
        public Nullable<int> SoLopDangMo { get; set; }
        public Nullable<int> TongHocVienDangHoc { get; set; }
    }
}
