//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QuanLyTrungTamNgoaiNgu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_TaiKhoan_Quyen
    {
        public string MATK { get; set; }
        public string TENDANGNHAP { get; set; }
        public bool TrangThaiHoatDong { get; set; }
        public string MaNV { get; set; }
        public string MaGV { get; set; }
        public string HoTenNguoiDung { get; set; }
        public string DanhSachQuyen { get; set; }
    }
}
